{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--2018-02-26 14:49:13--  https://www.dropbox.com/s/wson7j5ih0126zy/spooky.csv?dl=1\n",
      "Resolving www.dropbox.com (www.dropbox.com)... 162.125.3.1, 2620:100:6018:1::a27d:301\n",
      "Connecting to www.dropbox.com (www.dropbox.com)|162.125.3.1|:443... connected.\n",
      "HTTP request sent, awaiting response... 302 Found\n",
      "Location: https://dl.dropboxusercontent.com/content_link/8iAAg1S5JxyVJFxYFWrgXepA6tajtLgCjc7pCrIvHZ1MUTxWN5JAP6IQDTUpJ7FF/file?dl=1 [following]\n",
      "--2018-02-26 14:49:13--  https://dl.dropboxusercontent.com/content_link/8iAAg1S5JxyVJFxYFWrgXepA6tajtLgCjc7pCrIvHZ1MUTxWN5JAP6IQDTUpJ7FF/file?dl=1\n",
      "Resolving dl.dropboxusercontent.com (dl.dropboxusercontent.com)... 162.125.7.6, 2620:100:601d:6::a27d:506\n",
      "Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|162.125.7.6|:443... connected.\n",
      "HTTP request sent, awaiting response... 200 OK\n",
      "Length: 3295644 (3.1M) [application/binary]\n",
      "Saving to: ‘spooky.csv’\n",
      "\n",
      "spooky.csv          100%[===================>]   3.14M  11.3MB/s    in 0.3s    \n",
      "\n",
      "2018-02-26 14:49:14 (11.3 MB/s) - ‘spooky.csv’ saved [3295644/3295644]\n",
      "\n"
     ]
    }
   ],
   "source": [
    "!wget https://www.dropbox.com/s/wson7j5ih0126zy/spooky.csv?dl=1 -O spooky.csv"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os, sys\n",
    "from IPython import display\n",
    "import random\n",
    "def show_app(app, port = None, \n",
    "             width = \"100%\", \n",
    "             height = '800px', \n",
    "             offline = False,\n",
    "            in_binder = None):\n",
    "    if port is None:\n",
    "        port = random.choice(range(1000, 10000))\n",
    "    in_binder ='JUPYTERHUB_SERVICE_PREFIX' in os.environ if in_binder is None else in_binder\n",
    "    if in_binder:\n",
    "        base_prefix = '{}proxy/{}/'.format(os.environ['JUPYTERHUB_SERVICE_PREFIX'], port)\n",
    "        url = 'https://hub.mybinder.org{}'.format(base_prefix)\n",
    "        app.config.requests_pathname_prefix = base_prefix\n",
    "    else:\n",
    "        url = 'http://localhost:%d' % port\n",
    "        \n",
    "    iframe = '<a href=\"{url}\" target=\"_new\">Open in new window</a><hr><iframe src=\"{url}\" width={width} height={height}></iframe>'.format(url = url, \n",
    "                                                                                  width = width, \n",
    "                                                                                  height = height)\n",
    "    \n",
    "    display.display_html(iframe, raw = True)\n",
    "    if offline:\n",
    "        app.css.config.serve_locally = True\n",
    "        app.scripts.config.serve_locally = True\n",
    "    else:\n",
    "        app.css.config.serve_locally = False\n",
    "        app.scripts.config.serve_locally = False\n",
    "    return app.run_server(debug=False, # needs to be false in Jupyter\n",
    "                          host = '0.0.0.0',\n",
    "                          port=port)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "from interface import app"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<a href=\"https://hub.mybinder.org/user/4quantoss-trecs-aqf66wku/proxy/7430/\" target=\"_new\">Open in new window</a><hr><iframe src=\"https://hub.mybinder.org/user/4quantoss-trecs-aqf66wku/proxy/7430/\" width=100% height=800px></iframe>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://0.0.0.0:7430/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:17] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:18] \"\u001b[37mGET /_dash-dependencies HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:18] \"\u001b[37mGET /_dash-layout HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:18] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:18] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:22] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:22] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:25] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:25] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:27] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:27] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:34] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:34] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:38] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "[2018-02-26 14:49:38,845] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/dash/dash.py\", line 556, in dispatch\n",
      "    return self.callback_map[target_id]['callback'](*args)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/dash/dash.py\", line 513, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"/home/jovyan/interface.py\", line 146, in test\n",
      "    interface_obj.default_clean()\n",
      "  File \"/home/jovyan/iqss_interface.py\", line 63, in default_clean\n",
      "    self.clean_df[self.clean_df.columns[1]] = self.clean_df[self.clean_df.columns[1]].apply(utils.remove_non_ascii).to_frame()\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/pandas/core/series.py\", line 2551, in apply\n",
      "    mapped = lib.map_infer(values, f, convert=convert_dtype)\n",
      "  File \"pandas/_libs/src/inference.pyx\", line 1521, in pandas._libs.lib.map_infer\n",
      "  File \"/home/jovyan/utils.py\", line 144, in remove_non_ascii\n",
      "    return ''.join(stripped)\n",
      "  File \"/home/jovyan/utils.py\", line 143, in <genexpr>\n",
      "    stripped = (unicode(str(c), 'utf-8') for c in text if 0 < ord(c) < 127)\n",
      "NameError: name 'unicode' is not defined\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:38] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:48] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:49] \"\u001b[37mGET /_dash-dependencies HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:49] \"\u001b[37mGET /_dash-layout HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:49] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:49] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:54] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:55] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:59] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:49:59] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:50:00] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:50:00] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:50:06] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "[2018-02-26 14:50:06,256] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/dash/dash.py\", line 556, in dispatch\n",
      "    return self.callback_map[target_id]['callback'](*args)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/dash/dash.py\", line 513, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"/home/jovyan/interface.py\", line 202, in test\n",
      "    interface_obj.build_doc_freq()\n",
      "  File \"/home/jovyan/iqss_interface.py\", line 53, in build_doc_freq\n",
      "    self.freq_matrix = utils.build_freq_matrix(self.clean_df)\n",
      "  File \"/home/jovyan/utils.py\", line 68, in build_freq_matrix\n",
      "    frequency_matrix, bag_of_words = termdocument_matrix(dataframe)\n",
      "  File \"/home/jovyan/utils.py\", line 25, in termdocument_matrix\n",
      "    descriptions = [unicode(str(dscr), 'utf-8').split(\" \") for dscr in descriptions]\n",
      "  File \"/home/jovyan/utils.py\", line 25, in <listcomp>\n",
      "    descriptions = [unicode(str(dscr), 'utf-8').split(\" \") for dscr in descriptions]\n",
      "NameError: name 'unicode' is not defined\n",
      "127.0.0.1 - - [26/Feb/2018 14:50:06] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:50:11] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:50:11] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "[2018-02-26 14:50:19,075] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/dash/dash.py\", line 556, in dispatch\n",
      "    return self.callback_map[target_id]['callback'](*args)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/dash/dash.py\", line 513, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"/home/jovyan/interface.py\", line 645, in build_models\n",
      "    lsa_nt = utils.get_num_of_topics(interface_obj.clean_df)\n",
      "  File \"/home/jovyan/utils.py\", line 44, in get_num_of_topics\n",
      "    frequency_matrix, bag_of_words = termdocument_matrix(dataframe)\n",
      "  File \"/home/jovyan/utils.py\", line 25, in termdocument_matrix\n",
      "    descriptions = [unicode(str(dscr), 'utf-8').split(\" \") for dscr in descriptions]\n",
      "  File \"/home/jovyan/utils.py\", line 25, in <listcomp>\n",
      "    descriptions = [unicode(str(dscr), 'utf-8').split(\" \") for dscr in descriptions]\n",
      "NameError: name 'unicode' is not defined\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [26/Feb/2018 14:50:19] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:50:24] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:50:24] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "[2018-02-26 14:50:26,749] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/dash/dash.py\", line 556, in dispatch\n",
      "    return self.callback_map[target_id]['callback'](*args)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/dash/dash.py\", line 513, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"/home/jovyan/interface.py\", line 667, in get_similar\n",
      "    courses = interface_obj.iqss_model.get_similar(course_name, int(amount))\n",
      "TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'\n",
      "127.0.0.1 - - [26/Feb/2018 14:50:26] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:50:28] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:50:32] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:50:40] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:50:40] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:50:40] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "INFO:lda:n_documents: 19579\n",
      "INFO:lda:vocab_size: 3\n",
      "INFO:lda:n_words: 19579\n",
      "INFO:lda:n_topics: 10\n",
      "INFO:lda:n_iter: 1\n",
      "/srv/conda/lib/python3.6/site-packages/lda/utils.py:55: FutureWarning:\n",
      "\n",
      "Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.\n",
      "\n",
      "INFO:lda:<0> log likelihood: -66514\n",
      "INFO:lda:<0> log likelihood: -66482\n",
      "127.0.0.1 - - [26/Feb/2018 14:50:43] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "INFO:werkzeug:127.0.0.1 - - [26/Feb/2018 14:50:43] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "[2018-02-26 14:50:43,742] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/dash/dash.py\", line 556, in dispatch\n",
      "    return self.callback_map[target_id]['callback'](*args)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/dash/dash.py\", line 513, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"/home/jovyan/interface.py\", line 829, in build_cluster_graph\n",
      "    fig = cluster_obj.set_graph(slider_val2, dim)\n",
      "  File \"/home/jovyan/visualizations.py\", line 63, in set_graph\n",
      "    return self.create_plot()\n",
      "  File \"/home/jovyan/visualizations.py\", line 101, in create_plot\n",
      "    _lda_keys = self.get_lda_keys()\n",
      "  File \"/home/jovyan/visualizations.py\", line 152, in get_lda_keys\n",
      "    for i in xrange(self.X_topics_current.shape[0]):\n",
      "NameError: name 'xrange' is not defined\n",
      "127.0.0.1 - - [26/Feb/2018 14:50:43] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "INFO:werkzeug:127.0.0.1 - - [26/Feb/2018 14:50:43] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:50:43] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "INFO:werkzeug:127.0.0.1 - - [26/Feb/2018 14:50:43] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "INFO:lda:n_documents: 19579\n",
      "INFO:lda:vocab_size: 3\n",
      "INFO:lda:n_words: 19579\n",
      "INFO:lda:n_topics: 10\n",
      "INFO:lda:n_iter: 1\n",
      "INFO:lda:<0> log likelihood: -66514\n",
      "INFO:lda:<0> log likelihood: -66461\n",
      "127.0.0.1 - - [26/Feb/2018 14:50:46] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "INFO:werkzeug:127.0.0.1 - - [26/Feb/2018 14:50:46] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [26/Feb/2018 14:50:46] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "INFO:werkzeug:127.0.0.1 - - [26/Feb/2018 14:50:46] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "[2018-02-26 14:50:46,519] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1982, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1614, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1517, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/_compat.py\", line 33, in reraise\n",
      "    raise value\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1612, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/flask/app.py\", line 1598, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/dash/dash.py\", line 556, in dispatch\n",
      "    return self.callback_map[target_id]['callback'](*args)\n",
      "  File \"/srv/conda/lib/python3.6/site-packages/dash/dash.py\", line 513, in add_context\n",
      "    output_value = func(*args, **kwargs)\n",
      "  File \"/home/jovyan/interface.py\", line 829, in build_cluster_graph\n",
      "    fig = cluster_obj.set_graph(slider_val2, dim)\n",
      "  File \"/home/jovyan/visualizations.py\", line 63, in set_graph\n",
      "    return self.create_plot()\n",
      "  File \"/home/jovyan/visualizations.py\", line 101, in create_plot\n",
      "    _lda_keys = self.get_lda_keys()\n",
      "  File \"/home/jovyan/visualizations.py\", line 152, in get_lda_keys\n",
      "    for i in xrange(self.X_topics_current.shape[0]):\n",
      "NameError: name 'xrange' is not defined\n",
      "127.0.0.1 - - [26/Feb/2018 14:50:46] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "INFO:werkzeug:127.0.0.1 - - [26/Feb/2018 14:50:46] \"\u001b[1m\u001b[35mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    }
   ],
   "source": [
    "show_app(app)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
